let neighborhoods = [

    'West Philadelphia',
    'South Philadelphia',
    'Center City',
    'North Philadelphia',
    'Penn\'s Landing',
    'Manayunk',
    'Fairmount',
    'Fishtown',
    'Old City',
    'Chestnut Hill',
    'Northeast Philadelphia',
    'Rittenhouse Square',
    'Kensington',
    'Germantown',
    'Chinatown',
    'Northern Liberties',
    'Fairmount Park',
    'Frankford',
    'East Falls',
    'Roxborough',
    'Brewerytown',
    'Strawberry Mansion',
    'Port Richmond',
    'Society Hill',
    'Southwest Philadelphia',
    'Overbrook',
    'Queen Village',
    'Grays Ferry',
    'Nicetown-Tioga',
    'Hunting Park',
    'West Oak Lane',
    'Fitler Square Philadelphia',
    'Bridesburg',
    'Washington Square West',
    'Powelton Village',
    'Lawncrest',
    'Holmesburg',
    'Head house Square',
    'Bustleton',
    'Passyunk Square',
    'Pennsport',
    'Girard Estate',
    'Wynnfield',
    'Feltonville',
    'Kingsessing',
    'Rhawhurst',
    'Harrowgate',
    'Francisville',
    'Callowhill',
    'Devil\'s Pocket',
    'Spruce Hill'
];

export default neighborhoods;
